spring:
  profiles: cloud
  # datasource
  datasource:
    url: jdbc:mysql://mysql:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  # date
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  # freemarker
  freemarker:
    enabled: true
    request-context-attribute: request
    suffix: .ftl
    content-type: text/html
    template-loader-path: classpath:/templates/ftl/
    charset: UTF-8
    settings:
      number_format: 0.##
      default_encoding: UTF-8
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  # redis
  redis:
    database: 0
    host: redis
    password: tencentcloud
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 2

config:
  redis:
    enable: true
  upload:
    path: /data/resource
    ossPath: /data/oss-res
  mongodb:
    host: 172.16.0.4
    port: 27017
    userName: appboot
    password: baiduyun
    dbName: appboot
    option:
      connections-per-host: 10
      min-connections-per-host: 10
      threads-allowed-to-block-for-connection-multiplier: 10
      socket-timeout: 20000
      connect-timeout: 20000
      heartbeat-socket-timeout: 2000
      heartbeat-connect-timeout: 2000
      heartbeat-frequency: 10000
      max-wait-time: 10000