spring:
  profiles: desk
  # postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  # date
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  # mongo
#  data:
#    mongodb:
#      uri: mongodb://root:rootken@39.108.127.68:27017/ken
#      connections-per-host: 20
#      min-connections-per-host: 20
#      option:
#        threads-allowed-to-block-for-connection-multiplier: 10
#        socket-timeout: 0
#        heartbeat-socket-timeout: 20000
#        heartbeat-connect-timeout: 20000
#        heartbeat-frequency: 10000
  # freemarker
  freemarker:
    enabled: true
    request-context-attribute: request
    suffix: .ftl
    content-type: text/html
    template-loader-path: classpath:/templates/ftl/
    charset: UTF-8
    settings:
      number_format: 0.##
      default_encoding: UTF-8
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
  # redis
  redis:
    database: 0
    host: localhost
    password: 
    port: 6379
    jedis:
      timeout: 10000
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 2

config:
  redis:
    enable: true
  upload:
    path: D:/temp/dist
    ossPath: D:/temp/osstest
  mongodb:
    host: 106.12.103.25
    port: 27017
    userName: appboot
    password: baiduyun
    dbName: appboot
    option:
      connections-per-host: 10
      min-connections-per-host: 10
      threads-allowed-to-block-for-connection-multiplier: 10
      socket-timeout: 20000
      connect-timeout: 20000
      heartbeat-socket-timeout: 2000
      heartbeat-connect-timeout: 2000
      heartbeat-frequency: 10000
      max-wait-time: 10000
