version: '3'
services:
  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - /data/mysql/db:/var/lib/mysql
      - /data/mysql/conf/my.cnf:/etc/my.cnf
  redis:
    container_name: v-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /data/redis/db:/data
      - /data/redis:/etc/redis
    command: redis-server /etc/redis/redis.conf
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/nginx/conf.d:/etc/nginx/conf.d
      - /data/resource:/data/resource
      - /data/static-res:/data/static-res
  bootapp:
    container_name: v-bootapp
    restart: always
    build: ./bootapp
    working_dir: /bootapp
    volumes:
      - ./bootapp:/bootapp
      - /data/oss-res:/data/oss-res
      - /data/resource:/data/resource
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=cloud