version: '3'
services:
  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: /bin/bash -c "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0 && echo "Asia/shanghai" > /etc/timezone"
    volumes:
      - "/data/mysql/db:/var/lib/mysql"
      - "/data/mysql/conf:/etc/mysql/conf.d"
      - /etc/localtime:/etc/localtime:ro
  bootapp:
    container_name: v-bootapp
    restart: always
    build: ./bootapp
    working_dir: /bootapp
    volumes:
      - ./bootapp:/bootapp
      - ~/.m2:/root/.m2
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: /bin/bash -c "mvn clean spring-boot:run -Dspring-boot.run.profiles=docker && echo "Asia/shanghai" > /etc/timezone"
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - "/data/resource:/data/resource"
  redis:
    container_name: v-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "/data/redis/db:/data"
      - "./redis:/etc/redis"
    command: redis-server /etc/redis/redis.conf