version: '3'
services:
  mongodb:
    container_name: v-mongo
    image: mongo
    volumes:
      - /data/mongo/db:/data/db
#    command: --auth
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: baiduyun
    restart: always
    ports:
      - 27017:27017